### ISSUE TITLE
Cleanup Maven build

### ISSUE THREAD

**Issue by rhuss** [syndesisio/syndesis#1078]
* [ ] Fix parent to include all referenced version in `<dependencyManagement>`
* Introduce a concise Maven naming for directories, artifactIds and top-level package names.
  - [x] Every directory is reflected in the artifactid (e.g. `rest/dao` --> `rest-dao` artifactId)
  - [ ] Every module has a single top-level package (e.g. for `rest/dao` --> `io.syndesis.rest.dao`)
  - [x] The are `-` allowed in directory names but should be avoided (because of the point above).
  - [x] Directory structure should not be deeper than 2
  - [x] Avoid intermediated pom.xml which do not add functionality. Reference modules directly in the top-level parent pom
* Check the dependency graph:
  - [ ] Avoid circular dependencies at all cost
  - [ ] No dependencies for the runtimes to backend modules. We might weaken this restriction later on, but for now it helps in separating those two big blocks.
  - [x] Should we add a different Maven group for runtime jars ? 
* [x] Group Maven module in top-level "modules" which are reflected via GitHub labels `modules/...`

**Comment by paoloantinori** [comment]
this might have implications on other systems slow to pick up the change, so better doing earlier than later
