### ISSUE TITLE
API Provider

### ISSUE THREAD

**Issue by gaughan** [syndesisio/syndesis#3046]
## Feature Owner: Zoran, Luca, Nicola, Stan

As an expert integrator, I often want to be able to create an API provider as a way to invoke an integration.
I want to be able to provide my swagger definition or create an API definition via Apicurio. 
I want Fuse to provide me with details of my endpoint (hostname and path)
My expectation is that I can do this as part of the following workflow:

When I go to start an integration from an API Provider connector:
1. A new API card is available for API Provider (not API client connectors) as start connectors. I can select the API card.
2. On the next page I can ‘Upload Open API2.0 Specification’ or select ‘create API definition in Apicurio’ This is embedded Apicurio as exists today. I can either provide my own API definition here or I can create one on the fly. 
3. I am presented with the first operation or a list of all operations. I choose the operation I first want to configure for my integration.  All resource operations that were previously provided are displayed.
4. Fuse must validate that all resource operations have a flow or…
5. On successfully supplying an API definition, all operations are now integration flows and auto return 501 code if no flow is explicitly configured.
6. Supported content types (inbound and outbound) - JSON to be delivered first.

### DOD
- [x] I can create an API Provider connector by providing a swagger(OpenApi 2.0) definition.
- [x] I can create an API Provider connector by creating a swagger(OpenApi 2.0) definition on the fly with embedded apicurio.
- [x] I can invoke all the operations supplied via the endpoint provided.
- [x] Every operation has a flow.
- [x] Every flow can be different (have a different connector for example).
- [x] I can provide a different flow for each operation.
- [x] API is discoverable  (See #3407)
- [x] Data return is  illustrated in the UI and editable (able to apply mapping)

### UX Designs
- links in #3140 latest comments

**Comment by sjcox-rh** [comment]
Reference [slide deck](https://docs.google.com/presentation/d/1XGFd3GL98FivhReUwDR4CJtRPbApL5dILnjVi5Ju-lQ/edit?usp=sharing) for more details

Goal: After successfully creating provider connector, allow users to configure all actions defined by swagger file within integration workflow seamlessly

Questions:
* On first step of create API connector flow, have a add a way to create api definition in apicurio, will launch embedded apicurio. What should that look like?
* When does the user make the choice if it’s a client or provider connector? At the connector flow creation workflow? Can the decision to choose  an API provider or API client be deferred to the integration editor?
* Provide a visual on how to show an integration flow with multiple actions used for a provider (start connection) connector.
* Choose action page would change. User would have to configure all actions associated with swagger file created.
* Need to update flow so that user can configure all actions and jump back and forth between actions. Need to have a visual for actions that are not yet configured (alert, error??)
* Do they need to have a visual/ action within IVP to jump between action configurations? or just within right hand panel? or both?
* Dropdown or full page to toggle between actions?

**Comment by chirino** [comment]
@gaughan, @kcbabo I know it's not a priority, but I think it would be useful to think about a user that wants to implement an ad hoc API.  One that is designed directly while implementing an integration flow(s) without much thought going to a full on REST API.

I want to make sure our API provider story can eventually cope with this case too, because integrations are typically thought of as small glue code between systems and many times are built to handle tactical situations.

In this scenario, I think Apicurio might be over kill, and even if he did use it, shortly after the first API is implemented in production, he will start wanting to modify the API to add more bits to it.  So we need to make sure we can change and enhance existing API provider implementations.  How would that fit into this user story?

**Comment by gaughan** [comment]
@chirino So edit after publishing functionality? Rest by default seems reasonable tho no?

**Comment by chirino** [comment]
@gaughan yes, whats the story behind the workflow?

**Comment by gaughan** [comment]
@chirino I will set up a call to discuss in more detail.

**Comment by gaughan** [comment]
We decided on the call to make the decision "Provider or Client" at the connector level.

**Comment by heiko-braun** [comment]
@gaughan @sjcox-rh To fully support this we need support for data return flows, including mappings. @lburgazzoli Do you want to share your thoughts? I think this is missing from the DOD and requires a separate design.

**Comment by lburgazzoli** [comment]
We can add some information tot the starting action that can trigger to UI to automatically generate a virtual end step by default so a user can do mapping.

**Comment by gaughan** [comment]
Agreed, update DOD

**Comment by zregvart** [comment]
So I was thinking: are API Providers (bad name btw), connectors or integrations?

Do we expect users to implement multiple identical APIs as separate integrations? If so would it be bad UX to go through the API Provider wizard twice with the same specification?

Also how does a connector relate to multiple Camel routes that we need to implement separate flows of the API Provider based integration?

So if we approach implementing APIs instead of as creating connectors but as creating integrations we might be closer to what we're trying to model and implement at the same time.

Benefits:
 - Simpler user experience: upload OpenAPI specification get an integration that only needs flows defined
 - Easier on the UI as a lot of scaffolding can be done on the backend: defining a new Integration can be performed on the backend, along with all the flows (individual API operations), start and end actions with required datashapes
 - No changes to the Custom API Client we already support (less risk of breaking it)
 - It closer models what we require for Camel implementation, should be easier to implement

Drawbacks:
 - No connections (we kinda don't need them?)
 - New wizard to create integrations from specifications (could be benefit)

Perhaps it's worth considering.

**Comment by gashcrumb** [comment]
I'm on PTO now and next week but wanted to chime in and say +1 @zregvart

**Comment by TovaCohen** [comment]
In an integration created from an API provider, can I add a connection to some other application?

**Comment by sjcox-rh** [comment]
@heiko-braun @gaughan @lburgazzoli  in response to your comment about supporting data return flows within API providers. I couldn't join the PM call yesterday so Im not fully sure I understand this. Want to make sure I understand the requirements for the separate design being requested.  Thank you!

**Comment by dongniwang** [comment]
I'm not sure I'm following the conversation now... 

>Do we expect users to implement multiple identical APIs as separate integrations? If so would it be bad UX to go through the API Provider wizard twice with the same specification?

Why would the users go through the API Provider wizard twice? 

> So if we approach implementing APIs instead of as creating connectors but as creating integrations we might be closer to what we're trying to model and implement at the same time.

Can someone please explain a little bit more about this?

**Comment by zregvart** [comment]
I'll try, but let's do this in person next week, I'll try to create some diagrams to help visualise this.

>     Do we expect users to implement multiple identical APIs as separate integrations? If so would it be bad UX to go through the API Provider wizard twice with the same specification?
> 
> Why would the users go through the API Provider wizard twice?

In this concept we would not have connectors/connections for API Provider-based integrations, we would scaffold integrations based on the provided OpenAPI specification. To create a new, identical, API Provider-based integration the user would need to provide the same OpenAPI specification the second time to scaffold a new integration.

>     So if we approach implementing APIs instead of as creating connectors but as creating integrations we might be closer to what we're trying to model and implement at the same time.
> 
> Can someone please explain a little bit more about this?

Right now we have one integration modelled as one OpenShift pod containing one Camel route containing the steps of the single integration flow. Here the Camel route is representing the integration 1:1.

With API Provider-based integrations we need (assuming the multiple flow concept): one integration with multiple flows running as one OpenShift pod containing multiple Camel routes and Camel REST DSL configuration. Here we need to represent multiple Camel routes and Camel REST DSL configuration and the Connector model doesn't fit that -- we need something at a higher level. That is, defining a connector which can be applied as a connection/step part of the integration doesn't model well this situation, we need to generate something at a higher level from the OpenAPI specification, and this proposes that to be the integration model.

I know this is not the best explanation, I'll try to figure out a better way of demonstrating this.

**Comment by gaughan** [comment]
Inline comments:

> So I was thinking: are API Providers (bad name btw), connectors or integrations?

Agreed, let work on naming seperatly.

> Do we expect users to implement multiple identical APIs as separate integrations? If so would it be bad UX to go through the API Provider wizard twice with the same specification?

Not an expectation, but they could in theory.
> 
> Also how does a connector relate to multiple Camel routes that we need to implement separate flows of the API Provider based integration?
> 
> So if we approach implementing APIs instead of as creating connectors but as creating integrations we might be closer to what we're trying to model and implement at the same time.

This approach may not help us pave the way in the UI for functioality such as CBR.

> Benefits:
> 
> Simpler user experience: upload OpenAPI specification get an integration that only needs flows defined
> Easier on the UI as a lot of scaffolding can be done on the backend: defining a new Integration can be performed on the backend, along with all the flows (individual API operations), start and end actions with required datashapes
> No changes to the Custom API Client we already support (less risk of breaking it)
> It closer models what we require for Camel implementation, should be easier to implement
> Drawbacks:
> 
> No connections (we kinda don't need them?)
> New wizard to create integrations from specifications (could be benefit)
> Perhaps it's worth considering.

**Comment by heiko-braun** [comment]
@sjcox-rh Can you link the UX design proposals to either this one or #3140?

**Comment by gashcrumb** [comment]
>Can you link the UX design proposals to either this one or #3140?

#3140 links off to the designs, added that to the issue desrciption.

**Comment by dongniwang** [comment]
@gaughan @gashcrumb @lburgazzoli @nicolaferraro  - my understanding is that Zoran is on PTO this week, do we want to set up a meeting to walk through the latest design this week to help better scope the work for 7.2? Please let me know. 

cc: @amysueg @sjcox-rh @heiko-braun @paoloantinori

**Comment by gaughan** [comment]
@dongniwang good idea, meeting now set

**Comment by heiko-braun** [comment]
please put @lburgazzoli and @nicolaferraro  in the loop. They work on this feature together with Zoran.

**Comment by zregvart** [comment]
We done a bunch of this, no linked issues are left over. It's time.
