### ISSUE TITLE
[UX Design] Create UX design for API Provider 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3140]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

See user story #3046 

## Tasks involved 

- [x] receive UX request / identify priority 
- [x] verify user story and requirements [[user story](https://github.com/syndesisio/syndesis/issues/3046)]
- [x] initial UX design 
- [ ] Create visuals for API Provider and Return Path [issue #3359]
- [x] design review 
- [x] design iteration 
- [ ] design sign-off
- [ ] plan of action for implementation

**Comment by dongniwang** [comment]
API Provider - Provide API Definition (Dongni) https://redhat.invisionapp.com/share/WUNL4QGKP3E 
API Provider Exploration - 2 options list and dropdown (SJ) https://redhat.invisionapp.com/share/78NKMN0R59Y 
API Provider Exploration (Dongni)  https://redhat.invisionapp.com/share/WRNL4PF7SN5

**Comment by heiko-braun** [comment]
//cc @zregvart @lburgazzoli If you havn't done so already, please review/follow the designs above as well.

**Comment by dongniwang** [comment]
Latest design (v5) is here https://redhat.invisionapp.com/share/3CNPQLOKAEW.

**Comment by gaughan** [comment]
LGTM! thanks

**Comment by TovaCohen** [comment]
Apologies if I am asking about things that have been discussed and decided. I did not add comments to the design. It seemed easier to put my comments here:

Page 4, where you "Provide API Definition".
The title is "Start integration with an API" - are you all in agreement that this is the best title? I'm wondering if this should be:
"Start integration with an API call" with this descriptive text:
"Execute this integration when a client invokes an operation defined by this API."
If this does not accurately describe what is happening, can someone help me understand what exactly causes the integration to execute?

Page 5 - Use a URL
The text help under the URL input field says "...and create a new API definition that incorporates the updates." I think that should be ".. and create a new API connection that incorporates the updates." 

Page 11 - API Provider - Choose Operation
For the description under the title, how's this:
Click an operation to create an integration flow that implements that operation. 

Page 14 - I get a little lost here. I clicked an unimplemented operation and then I get a page that prompts me to "Add to Flow" or "Add to Integration". I don't know what to do. Under "Add to Flow" it tells me that I can add connections and steps to my integration. Should that be prompting me to add connections or steps to this flow? Hmmmmm. It looks like the only way to add to the integration is to add another flow, right? Maybe instead of "Add to Flow" and "Add to Integration" the two large prompts should be "Add Steps to Flow" and "Add Another Flow to Integration". 

Page 14 - Add to Flow, Add to Integration
The "Publish" button becomes available on this page. 
Why would I want to publish now? So far, I have selected an unimplemented operation. If I publish now, what would execution of this integration do? If I publish now, will I get prompted to specify some other things in my integration?

Page 15 - Create User - Configure Return Path
Is it optional to configure a return path?
What happens if I do not configure a return path?
I don't know what to suggest for a description of what the user is doing on this page because I don't understand what it means to set one status code. I'm struggling to understand why I want to set a status code on an operation that has not yet been executed. On the surface, it seems meaningless to do that. What am I missing?

Page 18 - Choose a Connection
To get here, on the page that prompts me to "Add to Flow" or "Add to Integration", I click "Add a  Connection". 
The description under "Choose a Connection" says "Click the connection that completes the integration." Is this correct? Will this connection complete the integration? I am wondering if this should be "Click the application that you want the integration to connect to. "

Side question - In an integration that starts with an API call, is the return to that API always the last connection in the integration?

Page 22 - Expanded IVP
When there are multiple flows, would the expanded IVP show them all?

**Comment by gaughan** [comment]
Answers in line:

Page 4, where you "Provide API Definition".
The title is "Start integration with an API" - are you all in agreement that this is the best title? I'm wondering if this should be:
"Start integration with an API call" with this descriptive text:
"Execute this integration when a client invokes an operation defined by this API."
If this does not accurately describe what is happening, can someone help me understand what exactly causes the integration to execute?
_No objections_

Page 5 - Use a URL
The text help under the URL input field says "...and create a new API definition that incorporates the updates." I think that should be ".. and create a new API connection that incorporates the updates." _Definition is accurate here_

Page 11 - API Provider - Choose Operation
For the description under the title, how's this:
Click an operation to create an integration flow that implements that operation.
_Sure. Or "Click an operation to implement an integration flow"_

Page 14 - I get a little lost here. I clicked an unimplemented operation and then I get a page that prompts me to "Add to Flow" or "Add to Integration". I don't know what to do. Under "Add to Flow" it tells me that I can add connections and steps to my integration. Should that be prompting me to add connections or steps to this flow? Hmmmmm. It looks like the only way to add to the integration is to add another flow, right? Maybe instead of "Add to Flow" and "Add to Integration" the two large prompts should be "Add Steps to Flow" and "Add Another Flow to Integration".
_We can discuss this further maybe_

Page 14 - Add to Flow, Add to Integration
The "Publish" button becomes available on this page.
Why would I want to publish now? So far, I have selected an unimplemented operation. If I publish now, what would execution of this integration do? If I publish now, will I get prompted to specify some other things in my integration?
_Publish is only available once you implement at least one operation._

Page 15 - Create User - Configure Return Path
Is it optional to configure a return path?
What happens if I do not configure a return path?
I don't know what to suggest for a description of what the user is doing on this page because I don't understand what it means to set one status code. I'm struggling to understand why I want to set a status code on an operation that has not yet been executed. On the surface, it seems meaningless to do that. What am I missing?
_It is optional. If you do not configure two options 501 gets returned or 200 if you implement the operation._

Page 18 - Choose a Connection
To get here, on the page that prompts me to "Add to Flow" or "Add to Integration", I click "Add a Connection".
The description under "Choose a Connection" says "Click the connection that completes the integration." Is this correct? Will this connection complete the integration? I am wondering if this should be "Click the application that you want the integration to connect to. "
_I believe this is correct, open to ideas tho._

Side question - In an integration that starts with an API call, is the return to that API always the last connection in the integration?
_Yes_

Page 22 - Expanded IVP
When there are multiple flows, would the expanded IVP show them all?
_No not currently, future potential tho._

**Comment by sjcox-rh** [comment]
Here is the latest designs (v6) for the API Provider flow based on the meeting and feedback received this morning!

https://redhat.invisionapp.com/share/CBNWDY58AHG

At your earliest convenience, please review the designs and let us know your approval of the design -- @gaughan @kcbabo @zregvart @lburgazzoli @TovaCohen @tplevko @gashcrumb @nicolaferraro 

Thank you!

fyi - @dongniwang @amysueg @michael-coker @seanforyou23

**Comment by gaughan** [comment]
LGTM! Thanks for the quick turnaround.

**Comment by nicolaferraro** [comment]
That's very good!

**Comment by lburgazzoli** [comment]
Very nice!

**Comment by gashcrumb** [comment]
So all looks good, but we're missing some kind of guidance for the integration list page and the integration detail page from that last link.

**Comment by gashcrumb** [comment]
@dongniwang awesome, yep, those are the ones.  @riccardo-forina ^^^

**Comment by riccardo-forina** [comment]
Question! In this [design](https://redhat.invisionapp.com/share/4JNR7J5DMNY#/screens/316053627) we show a badge with a number. I implemented it as the count of operations coming from the swagger file, but talking with @dongniwang I found that it should have been the number of _integrated_ operations.

But iterating on that, wouldn't both info be useful at the same time? Somethink like 5/20 for example, to indicate that 5 out of 20 operations have an integration defined.

Somewhat linked to this, I think it would be interesting to show the same thing [here](https://redhat.invisionapp.com/share/CBNWDY58AHG#/screens/318306620) instead of the Santa Hat, it would be a sort of progress indicator for the user while working.

WDYF?
