### ISSUE TITLE
[UX Design] Create UX design and guidelines for autosave 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3142]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

See user story #3048 

## Tasks involved / Steps to Reproduce

- [ ] receive UX request / identify priority 
- [ ] verify user story and requirements [[user story]](https://github.com/syndesisio/syndesis/issues/3048)
- [ ] initial design 
- [ ] design review 
- [ ] design iteration 
- [ ] design sign-off
- [ ] plan of action for implementation

**Comment by dongniwang** [comment]
@gaughan @heiko-braun @paoloantinori - Is autosave something we want for 7.4? If yes, we can start exploring a design guideline and solution. 

cc: @amysueg

**Comment by gaughan** [comment]
It's definitely on our roadmap. We need to figure out what will fit in 7.4 by the integration meeting

**Comment by dongniwang** [comment]
Thanks @gaughan ! In that case, can we change this issue to 7.x release? @heiko-braun

**Comment by heiko-braun** [comment]
@dongniwang Moved to 7.4 as per @gaughan 's comments
