### ISSUE TITLE
[UX Design] Create UX design for extension enhancment

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis#3158]
## This is a...

<pre><code>
[x] Feature request
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Documentation issue or request
</code></pre>

## The problem

See issues https://github.com/syndesisio/syndesis/issues/2809 and https://github.com/syndesisio/syndesis/issues/2808

## Tasks involved

- [x] receive UX request / identify priority 
- [x] verify user story and requirements 
- [x] initial design 
- [x] design review 
- [ ] design iteration 
- [ ] design sign-off
- [ ] plan of action for implementation

**Comment by dongniwang** [comment]
Hello all - 

[Here](https://redhat.invisionapp.com/share/WDN80PACBJU) is the design of extension enhancement, please review. 

@lburgazzoli @gashcrumb @kcbabo @gaughan @paoloantinori @TovaCohen 

cc: @amysueg @sjcox-rh @michael-coker @seanforyou23

**Comment by TovaCohen** [comment]
When the user is creating a connection, I think that the field label that you have in the design, "Library Extension" is fine, and for the tooltip, how about:

Select a previously uploaded extension that provides resources required by this connection, such as a JDBC driver. 

Is this the workflow for adding a library extension to an integration:

1. Crate the integration and save it as a draft.
2. Display the integration's summary, with the Details tab active.
3. In the Details tab, add one or more library extensions. 

I think I remember Luca saying that an integration can be associated with more than one library extension. Does the design support associating more than one extension with the integration?

In the integration summary page, Details tab, for the Library Extension field tooltip, how about:

Select one or more previously uploaded extensions that provide resources required to run this integration, such as an error handler. 

I like the new Versions tab!

This looks really good to me. Thanks Dongni!

**Comment by lburgazzoli** [comment]
I think the main points here are those mentioned also by @TovaCohen:

- it should be able to associate multiple extensions to the same integration
- to associate extension, the user need to go to the detail page but as it is possible to deploy the integration from the flow editor, a user may need to re-deploy the integration unless it saves the integration as a draft
