### ISSUE TITLE
Migrate UI to React

### ISSUE THREAD

**Issue by paoloantinori** [syndesisio/syndesis#4043]
Progress tracked on [Trello](https://trello.com/b/GNHCuA65/74-ui)

**Comment by riccardo-forina** [comment]
## UI

As a general rule, UI elements don't know anything about the app domain. All the props should be basic types (string, number, JSX element, etc.) and expose the event handler to add interactivity (onClick, etc.).

Text should always be passed in as a prop from the outside, to allow i18n of the app.

* **Main app layout**
  * [ ] Move the layout to @syndesis/ui
  * [ ] Migrate the masthead and sidebar to PF4
  * [ ] write storybooks
  * [ ] write tests
* **Content layout, scrollable with fixed header**
  * [ ] implementation
  * [ ] write storybooks
  * [ ] write tests
* **List view with toolbar helper**
  * [ ] (partially done) provide some kind of abstraction to reduce boilerplate when implementing the list view
  * [ ] write tests
* **Dashboard**
  * [ ] UI fixes (layout, css)
  * [ ] write storybooks
  * [ ] write tests
* **Connection/connector icon [helper](https://github.com/syndesisio/syndesis-react-poc/blob/7d268500c199df57faf974ea2a8fc5154403a6fb/packages/utils/src/getConnectionIcon.ts#L11-L10)**
  * [ ] proper implementation
  * [ ] write tests  
* **Connection/connector card**
  * [ ] cards are links, wrap them with a `Link` component and add the `to` prop
  * [ ] UI fixes (layout, css)
  * [ ] write storybooks
  * [ ] write tests
* **Connection details page layout**
  * [ ] implementation
  * [ ] write storybooks
  * [ ] write tests
* **Connection creation page layout** (it should be about just the wizard bar on the top)
  * [ ] implementation
  * [ ] write storybooks
  * [ ] write tests
* **Integration list item**
  * [ ] list items are links, wrap them with a `Link` component and add the `to` prop
  * [ ] UI fixes (layout, css)
  * [ ] actions (the drodown kebab) should be provided from the outside (as an array of objects with the proper shape to build the `MenuItem`s?)
  * [ ] write storybooks
  * [ ] write tests
* **Integration icon**
  * [ ] implementation
  * [ ] write storybooks
  * [ ] write tests
* **Integration status**
  * [ ] proper implementation
  * [ ] write storybooks
  * [ ] write tests
* **Integration detail page layout** 
  * **Details tab**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **Activity tab**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **Metrics tab**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
* **Integration import page layout**
  * [ ] implementation
  * [ ] write storybooks
  * [ ] write tests
* **Add to integration page layout**
  The initial page when editing an integration, with the "Add a Step" and "Add a Connection" buttons
  * [ ] implementation
  * [ ] write storybooks
  * [ ] write tests
* **IVP**
  * **layout** (top fixed header with the editable name, scrollable content with the steps)
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **connection element**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **step element**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **data-mapper element**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
* **Customization: API Client Connectors page layout**
  * **list**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **list empty page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **connector details page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **creation: page wizard bar**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **creation: upload page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **creation: review actions page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **creation: security page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **creation: review page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
* **Customization: Extensions page layout**
  * **list**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **list empty page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **extension details page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **extension import page layout**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
* **Settings page layout** 
  * **Header component**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **OAuth list item**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests
  * **OAuth list item expanded detail**
    * [ ] implementation
    * [ ] write storybooks
    * [ ] write tests

## Third party apps

* [x] Atlasmap
* [ ] Apicurio

## API

* **Rest**
  Figure out what we want to do with this component, if it should be a generic one supporting CRUD operations on a uri with conventions, or something else.
* [ ] **Test the existing components**
* [ ] To be extended with the missing API on a per-need basis

## Main app

* **JSON-to-form generator**
  * [ ] TBD
* **Dashboard**
  * [*] add module with its routes (just one, /)
  * [*] / page component
  * [ ] pass the right actions to each integration
  * [ ] set up the i18n labels
  * [ ] write tests
* **Context: integrations**
  * [ ] view action (redirect to the right url)
  * [ ] start action
  * [ ] can start action?
  * [ ] stop action
  * [ ] can stop action?
  * [ ] delete action
  * [ ] can delete action?
  * [ ] replace draft action
  * [ ] can replace draft action?
  * [ ] unpublish action
  * [ ] can unpublish action?
  * [ ] actions generator helper (to feed the drodown kebab)
* **Module: integrations**
  * [ ] add module with its routes
  * **Integrations list route** (/integrations)
    * [ ] page component
    * [ ] set up the i18n labels
    * [ ] write tests
  * **Integration import list route** (/integrations/import)
    * [ ] page component
    * [ ] set up the i18n labels
    * [ ] write tests
  * **Single integration route** (/integrations/:integrationId)
    * [ ] redirect to the details route
    * [ ] Export action
    * **integration details route** (/integrations/:integrationId/details)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **integration activity route** (/integrations/:integrationId/activity)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **integration metrics route** (/integrations/:integrationId/metrics)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **integration editor route** (/integrations/:integrationId/edit)
  * **SubModule: integration editor**
    * TBD
* **Module: connections**
  * [ ] add module with its routes
  * **connections list route** (/connections)
    * [ ] page component
    * [ ] set up the i18n labels
    * [ ] write tests
  * **connection import list route** (/connections/import)
    * [ ] page component
    * [ ] set up the i18n labels
    * [ ] write tests
  * **Single connection route** (/connections/:connectionId)
    * [ ] page component
    * [ ] set up the i18n labels
    * [ ] write tests
  * **Connection creation route** (/connections/create)
    * [ ] redirect to the select connector route
    * **Select connector route** (/connections/create/connetion-basic)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **Configure connection route** (/connections/create/configure-fields)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **Name connection route** (/connections/create/review)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
* **Module: customization**
  * [ ] redirect to API Client Connectors route
  * **API Client Connectors route**
    * **list** (/customizations/api-connector)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **connector details route** (/customizations/api-connector/:connectorId)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **connector creation route** (/customizations/api-connector/create)
      * [ ] redirect to the Upload OpenAPI specification route
      * **Upload OpenAPI specification route** (/customizations/api-connector/create/upload)
        * [ ] page component
        * [ ] set up the i18n labels
        * [ ] write tests
      * **Review Actions route** (/customizations/api-connector/create/review)
        * [ ] page component
        * [ ] set up the i18n labels
        * [ ] write tests
      * **Specify security route** (/customizations/api-connector/create/security)
        * [ ] page component
        * [ ] set up the i18n labels
        * [ ] write tests
      * **Review route**  (/customizations/api-connector/create/review)
        * [ ] page component
        * [ ] set up the i18n labels
        * [ ] write tests
  * **Extensions route**
    * **list route** (/customizations/extensions)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
    * **import route** (/customizations/extensions/import)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests
* **Module: settings** (/settings)
  * [ ] redirect to the OAuth Application management route
  * **OAuth Application management route**
    * **list** (/settings/oauth-clients)
      * [ ] page component
      * [ ] set up the i18n labels
      * [ ] write tests

**Comment by riccardo-forina** [comment]
☝️consider that as a placeholder track to follow in our planning meeting

**Comment by gashcrumb** [comment]
Was adding high-level items [here](https://docs.google.com/document/d/1QpEY2p_LZTkkVnZGoJQ3x3gqq9hQ4Hh4ohOfoGHCCWM/edit) to eventually add to this epic, but your list is more detailed.

**Comment by gashcrumb** [comment]
I'm gonna clean up the epic comments so the list is in the epic description.

**Comment by gashcrumb** [comment]
I would say for any of these pages/UI components that get worked on it's probably worth checking with UXD as to the most current design, if there's an updated design should we consider implementing that vs. just doing a 1:1 port of the current implementation?

**Comment by riccardo-forina** [comment]
It makes sense

**Comment by gashcrumb** [comment]
We did this.

**Comment by riccardo-forina** [comment]
![cheering](https://media.giphy.com/media/xT5LMqPBclx4HKdZXG/source.gif)
