### ISSUE TITLE
Jira Connector

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#4828]
See also **https://issues.jboss.org/browse/ENTESB-11513**

Jira Connector
As a citizen user I want to be able to connect to Jira. Jira details such as url and credentials should be provided in a similar to existing connectors.

DoD

I can **create** Jira issues including filed data such as
- component
- assignee
- watchee 
- issue type
- priority
- attachment

I can **read** Jira issues.

I can **update** Jira issues including filed data such as

- component
- assignee
- watchee 
- issue type
- priority
- attachment

I can **delete** Jira issues.

I want to be able to **comment** on an issue.

I want to be able to add my own **Jira query**.

I want to be able to transition to status Done or other available status.

If possible, we can look to get a list of required fields (or any other dynamic data) in the UI

The feature owner has confirmed one of the following:
--There is an initial draft of the user doc for this feature.
--The writer acknowledges receiving enough information from engineering to write the initial draft of the user doc for this feature.

Sub-Tasks
camel-jira component **Done** Waiting PR review
- [x] Add OAuth authentication
- [x] Add features as described above (edit issue, delete issue, update issue, add comment) 
- [x] Add tests
- [x] Write documentation
- [x] Write camel-jira example

jboss-fuse/camel jira component
- [x] Port camel-jira to jboss-fuse/camel fork

syndesis jira connector
- [x] Write jira.json and customizers
- [ ] Add tests
- [ ] Write documentation
- [ ] Add quickstart

**Comment by claudio4j** [comment]
Started work on the [new camel-jira-rest component](https://issues.apache.org/jira/browse/CAMEL-13390)

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11513**
