### ISSUE TITLE
Installation Method Consolidation 

### ISSUE THREAD

**Issue by heiko-braun** [syndesisio/syndesis#6285]
See also **https://issues.jboss.org/browse/ENTESB-11489**

### Tasks

- [x] The Syndesis operator must be able to create cluster resources like the Syndesis CRD, Camel-K CRDs
- [x] The Syndesis operator have to deploy itself, it has to be able to create the Operator DC, Operator Role and RoleBinding
- [ ] Migrate the install process from [fuse online install](https://github.com/syndesisio/fuse-online-install) to the operator. https://github.com/syndesisio/syndesis/issues/6330 https://github.com/syndesisio/syndesis/issues/6378 https://github.com/syndesisio/syndesis/issues/6418
- [ ] Move the update process out of Docker image and shell magic to go
- [ ] Migrate update from [fuse online install](https://github.com/syndesisio/fuse-online-install)
- [x] Create integration tests https://github.com/syndesisio/syndesis/pull/6354
- [ ] Consolidate documentation https://github.com/syndesisio/syndesis/issues/6356

**Comment by chirino** [comment]
@heiko-braun that’s a good list of pending work.

**Comment by heiko-braun** [comment]
Credits go to @lgarciaaco , he come up with this

**Comment by heiko-braun** [comment]
Migrated to **https://issues.jboss.org/browse/ENTESB-11489**
